name: climate-env
channels:
  - conda-forge
dependencies:
  - pandas=2.2.2
  - python=3.11.4
  - pip=25.3
  - ipykernel=7.1.0
  - altair-all=5.4
  - matplotlib=3.10.8
  - scikit-learn=1.7.2
  - pyyaml=6.0.3
  - conda-lock=3.0.4
